### ISSUE TITLE
[BUG] Auto-filled username shows up on the Grand Exchange search menu

### ISSUE THREAD

**Issue by sumsare** [EwyBoy/Friends-House#7]
When opening the grand exchange buy menu to search for an item to buy, the autofilled name will display underneath the text "What would you like to buy?". This happened after I'd already used my friend's house in the session, however it's likely it happens before as well.

![image](https://github.com/user-attachments/assets/40bdfdf7-2828-43bf-9452-a1e34e05e1df)

**Comment by EwyBoy** [comment]
Thanks for the report on this issue. I will investigate the situation further and get back to you with the details of the issue as soon as possible.

Should not be too much trouble to fix. Likely an oversight on my part.

**Comment by EwyBoy** [comment]
Issue has been addressed and fixed in my latest update. I have a PR active now for the plugin hub for the plugin to be updated.

**Comment by EwyBoy** [comment]
Fixed
